name: Run tests

on: [push, pull_request]

jobs:
  run-tests:
    env:
      not_in_conda: "[]"

    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7"]

    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:

      # Setup Python/pip
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge
          python-version: ${{ matrix.python-version }}
        if: ${{ runner.os == 'Linux' && !contains(fromJSON(env.not_in_conda), matrix.python-version) }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ runner.os != 'Linux' || contains(fromJSON(env.not_in_conda), matrix.python-version) }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Linux/Unix
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m ensurepip
          python -m pip install --upgrade pip setuptools wheel
          pip --version
          pip install --upgrade virtualenv "tox >= 2.0, < 4"
      - name: Set TOXENV
        run: |
          import os, sys
          ld_library_path = None
          if hasattr(sys, 'pypy_version_info'):
            toxenv = 'pypy3'
          else:
            pyver = '%d%d' % tuple(sys.version_info[:2])
            if os.name == 'posix':
              if pyver == '27':  # Python 2.7 on Linux requires `$LD_LIBRARY_PATH`
                ld_library_path = os.path.join(
                  os.path.dirname(os.path.dirname(sys.executable)), 'lib')
            toxenv = 'py%s' % pyver
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            if ld_library_path:
              f.write('LD_LIBRARY_PATH=' + ld_library_path + '\n')
            f.write('TOXENV=' + toxenv + '\n')
        shell: python

      - name: Run tox targets for ${{ matrix.python-version }}
        run: |
          python -c "import os; print(os.environ['TOXENV'])"
          tox --version
          tox
